### ISSUE TITLE
Offered Hosting of docs under subdomain. Requirement Starlight and Cloudflare

### ISSUE THREAD

**Issue by Fryuni** [astrolicious/astrolicious#16]
To be discussed, I don't think Cloudflare should be a requirement

**Comment by alexanderniebuhr** [comment]
to clarify, I meant if we offer hosting maintenance, meaning we take care of deployment and costs. It wouldn't work for any platform, we need to use one platform for that. Otherwise the only thing we could offer is a DNS record pointing to something else vs. offering to take care of deployment & hosting for an docs repository.

**Comment by florian-lefebvre** [comment]
ah i see. i think we should only offer pointing the dns

**Comment by alexanderniebuhr** [comment]
We can do that yeah, what about projects which can't afford hosting themselves?

**Comment by florian-lefebvre** [comment]
I think they all can, we can redirect them to netlify oss program to have a free generous plan

**Comment by alexanderniebuhr** [comment]
Let's start with offering DNS configuration first only, and see how projects use it, we can always add more stuff in the future. Then I don't think we need any requirement, even Starlight could be optional. It would be great for projects to use it, but if docs are clear and fitting to the project, I don't think we should force anything.

**Comment by alexanderniebuhr** [comment]
Only offering DNS for now, `CNAME` but preferable `A`/`AAAA` records. Will be part of the Onboarding Issue Template.
